# Generated by Django 4.0.6 on 2022-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Faculty_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Email', models.EmailField(max_length=80, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('Category', models.CharField(default='Student', max_length=20)),
                ('Current_Year', models.CharField(max_length=20, null=True)),
                ('Designation', models.CharField(max_length=50, null=True)),
                ('Profile_pic', models.ImageField(default='static/profile-default.png', upload_to='Profile_pic/')),
            ],
        ),
    ]
