# Generated by Django 4.0.6 on 2022-09-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=80)),
                ('OTP', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
