# Generated by Django 4.0.6 on 2022-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0002_otp_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_faculty_profile',
            name='DOB_day',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student_faculty_profile',
            name='DOB_month',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
